# Generated by Django 3.1.4 on 2021-01-20 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_id', models.IntegerField()),
                ('breed_name', models.CharField(max_length=200)),
                ('target', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=75)),
                ('stage', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('date_hatched', models.DateField()),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('birds_placed', models.IntegerField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.breed')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.IntegerField()),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField()),
                ('body_weight', models.FloatField()),
                ('body_uniform', models.CharField(max_length=10)),
                ('feed_rate', models.IntegerField()),
                ('feed_formula', models.CharField(max_length=75)),
                ('water_rate', models.CharField(max_length=75)),
                ('lay_rate', models.FloatField()),
                ('liveability', models.FloatField()),
                ('death_mortality', models.FloatField()),
                ('egg_weight', models.FloatField()),
                ('age_week', models.IntegerField()),
                ('age_daily', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock', models.CharField(max_length=75)),
                ('vaccine', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=75)),
                ('method', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deaths_mortality', models.IntegerField()),
                ('deaths_culls', models.IntegerField()),
                ('body_weight', models.FloatField()),
                ('body_uniformity', models.CharField(max_length=75)),
                ('feed_consumed', models.FloatField()),
                ('feed_delivered', models.FloatField()),
                ('feed_formula', models.CharField(max_length=75)),
                ('water_consumed', models.FloatField()),
                ('temperature_outside', models.FloatField()),
                ('temperature_inside', models.FloatField()),
                ('eggs_broken', models.FloatField()),
                ('eggs_sold', models.IntegerField()),
                ('egg_weight', models.IntegerField()),
                ('notes', models.CharField(max_length=200)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.flock')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.owner')),
            ],
        ),
        migrations.CreateModel(
            name='BreedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.breed')),
            ],
        ),
    ]
