# Generated by Django 3.1.4 on 2021-02-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='temperature_outside',
        ),
        migrations.AddField(
            model_name='flock',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.farm'),
        ),
        migrations.AddField(
            model_name='flock',
            name='flock_id',
            field=models.CharField(default='default', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='eggs_produced',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='date_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='flock',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.house'),
        ),
        migrations.AlterField(
            model_name='house',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.farm'),
        ),
        migrations.AlterField(
            model_name='record',
            name='body_uniformity',
            field=models.CharField(choices=[('uniform', 'uniform'), ('un-uniform', 'un-uniform')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='body_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='deaths_culls',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='deaths_mortality',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='egg_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='eggs_broken',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='eggs_sold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='feed_consumed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='feed_delivered',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='flock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.flock'),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='temperature_inside',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='water_consumed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flocks.flock'),
        ),
        migrations.AddField(
            model_name='farm',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flocks.country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='feed_formula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.feedformula'),
        ),
    ]
