# Generated by Django 3.1.4 on 2021-02-02 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0002_auto_20210202_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flock',
            name='farm',
        ),
        migrations.AlterField(
            model_name='farm',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.country'),
        ),
    ]
