# Generated by Django 3.1.4 on 2021-02-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0003_auto_20210202_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='flock_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
