# Generated by Django 3.1.4 on 2021-03-12 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flocks', '0004_auto_20210202_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flock',
            name='flock_id',
            field=models.CharField(default='Default', max_length=200),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='age_daily',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='age_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='body_uniform',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='body_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='death_mortality',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='egg_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='feed_formula',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='feed_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='lay_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='liveability',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='target',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='targetdetails',
            name='water_rate',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date_expiration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='flock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flocks.flock'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccine',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.CreateModel(
            name='FarmAttendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flocks.country')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farm',
            name='attendent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='flocks.farmattendent'),
        ),
    ]
