# Generated by Django 3.1.4 on 2021-03-12 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0006_auto_20210312_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='attendent',
        ),
        migrations.RemoveField(
            model_name='farmattendent',
            name='country',
        ),
        migrations.AddField(
            model_name='farmattendent',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flocks.farm'),
        ),
        migrations.AddField(
            model_name='farmattendent',
            name='last_name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmattendent',
            name='name',
            field=models.CharField(default='defult', max_length=200),
            preserve_default=False,
        ),
    ]
