# Generated by Django 3.1.4 on 2021-03-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flocks', '0007_auto_20210312_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmattendent',
            name='uid',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
